name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '>=3.9'

    - name: Install pipenv
      run: pip install pipenv

    - name: check dependencies
      run: which python3

    - name: Install dependencies
      run: pipenv sync --dev

    - name: Run tests
      run: pipenv run make test

    - name: Run black
      run: pipenv run make black 
