name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv sync --dev

    - name: Run tests
      run: make tests
      
    - name: Run black
      run: make black
